global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'postgres_metrics'
    static_configs:
      - targets: ['postgres-exporter:9187'] 

  - job_name: 'rabbitmq_metrics'
    static_configs:
      - targets: ['rabbitmq:15672']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']